training:
  epochs: 10
  lr: 0.01
  device: cuda

dataset:
  steps: 5

dataloader:
  batch_size: 64
  num_workers: 4
  pin_memory: false
  drop_last: true

model:
  e1:
    synapse:
      out_channels: 32
      kernel_size: [1, 3, 3]
      stride: [1, 2, 2]
      padding: [0, 0, 0]
    neuron:
      dynamics:
        leak_i: [-2.0, 0.5]
        leak_v: [-2.0, 0.5]
        thresh: [0.5, 0.0]
      learnable: [leak_i, leak_v, thresh]
      spike_fn:
        name: ArcTan
        shape: [1.0, 10.0]
  e2:
    synapse:
      out_channels: 64
      kernel_size: [1, 3, 3]
      stride: [1, 2, 2]
      padding: [0, 0, 0]
    neuron:
      dynamics:
        leak_i: [-2.0, 0.5]
        leak_v: [-2.0, 0.5]
        thresh: [0.5, 0.0]
      learnable: [leak_i, leak_v, thresh]
      spike_fn:
        name: ArcTan
        shape: [1.0, 10.0]
  p1:
    out_features: 10
    bias: true
